services:
  - type: web
    name: stage-management-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar -Dspring.profiles.active=prod target/STAGE-MANAGEMENT-BACKEND-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
